---
settings:
  name: NetApp Disaster Recovery
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação de recuperação de desastres da NetApp
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - section: reference
  - title: Perguntas frequentes
    url: "/get-started/dr-faq.html"
  - section: support
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
