= Funções de usuário no NetApp Disaster Recovery
:allow-uri-read: 




=== Funções de usuário no NetApp Disaster Recovery

O NetApp Disaster Recovery agora emprega funções para controlar o acesso que cada usuário tem a recursos e ações específicos.

O serviço usa as seguintes funções específicas do NetApp Disaster Recovery.

* *Administrador de recuperação de desastres*: execute quaisquer ações no NetApp Disaster Recovery.
* *Administrador de failover de recuperação de desastres*: execute ações de failover e migração no NetApp Disaster Recovery.
* *Administrador do aplicativo de recuperação de desastres*: Crie e modifique planos de replicação e inicie failovers de teste.
* *Visualizador de recuperação de desastres*: visualize informações no NetApp Disaster Recovery, mas não pode executar nenhuma ação.


Se estiver clicando no serviço NetApp Disaster Recovery e configurando-o pela primeira vez, você deverá ter a permissão *SnapCenterAdmin* ou ter a função *Organization Admin*.

Para obter detalhes, consulte  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Funções e permissões do usuário no NetApp Disaster Recovery"] .

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre funções de acesso para todos os serviços"^] .



=== Outras atualizações no NetApp Disaster Recovery

* Descoberta de rede aprimorada
* Melhorias de escalabilidade:
+
** Filtragem dos metadados necessários em vez de todos os detalhes
** Melhorias na descoberta para recuperar e atualizar recursos de VM mais rapidamente
** Otimização de memória e otimização de desempenho para recuperação e atualização de dados
** Melhorias na criação de clientes do vCenter SDK e no gerenciamento de pools


* Gerenciamento de dados obsoletos na próxima descoberta agendada ou manual:
+
** Quando uma VM é excluída no vCenter, o NetApp Disaster Recovery agora a remove automaticamente do plano de replicação.
** Quando um armazenamento de dados ou rede é excluído no vCenter, o NetApp Disaster Recovery agora o exclui do plano de replicação e do grupo de recursos.
** Quando um cluster, host ou datacenter é excluído do vCenter, o NetApp Disaster Recovery agora o exclui do plano de replicação e do grupo de recursos.


* Agora você pode acessar a documentação do Swagger no modo anônimo do seu navegador.  Você pode acessá-lo no NetApp Disaster Recovery na opção Configurações > Documentação da API ou diretamente no seguinte URL no modo anônimo do seu navegador: https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentação do Swagger"^] .
* Em algumas situações, após uma operação de failback, o iGroup foi deixado para trás após a conclusão da operação.  Esta atualização remove o iGroup se ele estiver obsoleto.
* Se o FQDN do NFS foi usado no plano de replicação, o NetApp Disaster Recovery agora o resolve para um endereço IP.  Esta atualização é útil se o FQDN não puder ser resolvido no site de recuperação de desastres.
* Melhorias no alinhamento da interface do usuário
* Melhorias no log para capturar os detalhes de dimensionamento do vCenter após a descoberta bem-sucedida

