= A BlueXP disaster recovery agora é NetApp Disaster Recovery
:allow-uri-read: 




[[bluexp-disaster-recovery-is-now-netapp-disaster-recovery]]
=== A BlueXP disaster recovery agora é NetApp Disaster Recovery

A BlueXP disaster recovery foi renomeada para NetApp Disaster Recovery.



[[bluexp-is-now-netapp-console]]
=== BlueXP agora é NetApp Console

O NetApp Console, construído sobre a base aprimorada e reestruturada do BlueXP, oferece gerenciamento centralizado do armazenamento NetApp e dos NetApp Data Services em ambientes locais e em nuvem com nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, altamente segura e em conformidade.

Para obter detalhes sobre o que mudou, consulte o link:https://docs.netapp.com/us-en/console-relnotes/index.html["Notas de versão do NetApp Console"].



[[other-updates]]
=== Outras atualizações

* O suporte para o Amazon Elastic VMware Service (EVS) com o Amazon FSx for NetApp ONTAP estava em uma prévia pública. Com este lançamento, ele agora está disponível para o público em geral. Para mais detalhes, consultelink:../reference/evs-deploy-guide-introduction.html["Introdução ao NetApp Disaster Recovery usando o Amazon Elastic VMware Service e o Amazon FSx for NetApp ONTAP"] .
* Melhorias na descoberta de armazenamento, incluindo tempos de descoberta reduzidos para implantações locais
* Suporte ao Gerenciamento de Identidade e Acesso (IAM), incluindo controle de acesso baseado em função (RBAC) e permissões de usuário aprimoradas
* Suporte de visualização privada para solução Azure VMware e Cloud Volumes ONTAP. Com esse suporte, agora você pode configurar a proteção de recuperação de desastres do local para a solução Azure VMware usando o armazenamento Cloud Volumes ONTAP .

