= Excluir um datastore dos planos de replicação
:allow-uri-read: 




=== Excluir um datastore dos planos de replicação

Ao criar um plano de replicação no Disaster, agora você pode excluir datastores específicos da replicação. Para situações em que uma VM está configurar para usar vários datastore, isso permite limitar quais serão replicados.

Para obter detalhes, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.adoc["Crie um plano de replicação"^].



=== Validação de senha removida da senha do vCenter

A Recuperação de Desastres removeu as restrições de senha no vCenter para permitir senhas que contenham espaços.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/evs-deploy-guide-add-vcenters.html["Adicionar clusters locais e do Amazon EVS vCenter no NetApp Disaster Recovery"^].



=== Novo submenu de plano de replicação

O recurso de Recuperação de Desastres agora inclui novas opções de menu para acionar atualizações do vCenter a partir do painel do plano de replicação. Você pode acessar o submenu no menu de ações do painel do plano de replicação: selecione **Integridade do Plano** e, em seguida, **Atualizar origem vCenter / Atualizar destino vCenter**.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#modify-a-replication-plan["Modificar um plano de replicação"^].



=== Descoberta de rede aprimorada

Disaster Recovery agora inclui descoberta de rede aprimorada para oferecer suporte a uma gama mais ampla de configurações de rede.
