---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Introdução ao NetApp Disaster Recovery usando Amazon EVS e Amazon FSx for NetApp ONTAP. 
---
= Introdução ao NetApp Disaster Recovery usando o Amazon Elastic VMware Service e o Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
Cada vez mais, os clientes têm se tornado mais dependentes de infraestruturas virtualizadas para cargas de trabalho de computação de produção, como aquelas baseadas no VMware vSphere.  À medida que essas máquinas virtuais (VMs) se tornaram mais críticas para seus negócios, os clientes precisam protegê-las dos mesmos tipos de desastres que seus recursos de computação física.  As soluções de recuperação de desastres (DR) oferecidas atualmente são complexas, caras e exigem muitos recursos.  A NetApp, maior provedora de armazenamento usada para infraestruturas virtualizadas, tem interesse em garantir que as VMs de seus clientes sejam protegidas da mesma forma que protegemos dados hospedados em armazenamento ONTAP de qualquer tipo.  Para atingir esse objetivo, a NetApp criou o serviço NetApp Disaster Recovery .

Um dos principais desafios de qualquer solução de DR é gerenciar o custo incremental de compra, configuração e manutenção de recursos adicionais de computação, rede e armazenamento apenas para fornecer uma infraestrutura de replicação e recuperação de DR.  Uma opção popular para proteger recursos virtuais críticos no local é usar recursos virtuais hospedados na nuvem como infraestrutura de replicação e recuperação de DR.  A Amazon é um exemplo de uma solução que pode fornecer recursos econômicos e compatíveis com infraestruturas de VM hospedadas NetApp ONTAP .

A Amazon lançou seu Amazon Elastic VMware Service (Amazon EVS), que habilita o VMware Cloud Foundation dentro de sua nuvem privada virtual (VPC).  O Amazon EVS oferece a resiliência e o desempenho da AWS, juntamente com o software e as ferramentas familiares da VMware, permitindo que os Amazon EVS vCenters sejam integrados como uma extensão da sua infraestrutura virtualizada local.

Embora o Amazon EVS venha com recursos de armazenamento incluídos, o uso de armazenamento nativo pode reduzir sua eficácia para organizações com cargas de trabalho pesadas de armazenamento.  Nesses casos, a combinação do Amazon EVS com o Amazon FSx for NetApp ONTAP (Amazon FSxN) pode fornecer uma solução de armazenamento mais flexível.  Além disso, ao usar soluções de armazenamento NetApp ONTAP no local para hospedar sua infraestrutura VMware, usar o Amazon EVS com o FSx para ONTAP significa que você obtém os melhores recursos de proteção e interoperabilidade de dados entre suas infraestruturas no local e hospedadas na nuvem.

Para obter informações sobre o Amazon FSx for NetApp ONTAP, consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introdução ao Amazon FSx for NetApp ONTAP"^] .
