---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Introdução ao NetApp Disaster Recovery usando Amazon EVS e Amazon FSx for NetApp ONTAP. 
---
= Saiba mais sobre o NetApp Disaster Recovery com o Amazon Elastic VMware Service e Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery ajuda a proteger as cargas de trabalho do VMware replicando dados de ambientes locais para Amazon Exchange Virtual Server e Amazon FSx for NetApp ONTAP para recuperação de desastres.

Um dos principais desafios de qualquer solução de DR é gerenciar o custo incremental de compra, configuração e manutenção de recursos adicionais de computação, rede e armazenamento apenas para fornecer uma infraestrutura de replicação e recuperação de DR.  Uma opção popular para proteger recursos virtuais críticos no local é usar recursos virtuais hospedados na nuvem como infraestrutura de replicação e recuperação de DR.  A Amazon é um exemplo de uma solução que pode fornecer recursos econômicos e compatíveis com infraestruturas de VM hospedadas NetApp ONTAP .

A Amazon lançou o Amazon Elastic VMware Service (Amazon Exchange Virtual Server), que permite o uso do VMware Cloud Foundation em sua nuvem privada (VPC). O Amazon Exchange Virtual Server oferece a resiliência e o desempenho da AWS, juntamente com o software e as ferramentas familiares da VMware, permitindo que os Amazon Exchange Virtual Server vCenters se integrem à sua infraestrutura virtualizada local.

Embora o Amazon Exchange Virtual Server inclua recursos de storage, o uso do storage nativo pode reduzir sua eficácia para organizações com cargas de trabalho que demandam grande quantidade de armazenamento. Nesses casos, combinar o Amazon Exchange Virtual Server com o Amazon FSx for NetApp ONTAP storage (Amazon FSxN) pode fornecer uma solução de storage mais flexível. Além disso, ao usar soluções de storage NetApp ONTAP on-premises para hospedar sua infraestrutura VMware, o uso do Amazon Exchange Virtual Server com o FSx for ONTAP oferece recursos de interoperabilidade e proteção de dados em ambientes on-premises e na nuvem.

Para obter informações sobre o Amazon FSx for NetApp ONTAP, consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introdução ao Amazon FSx for NetApp ONTAP"^] .
