---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: O agente do NetApp Console orquestra a conexão e o gerenciamento entre o NetApp Console e recursos de storage em nuvem ou locais. 
---
= Instalar o agente do NetApp Console para NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Um agente do NetApp Console permite que você conecte suas implantações do NetApp Console à sua infraestrutura para orquestrar soluções com segurança em ambientes AWS, Azure, Google Cloud ou locais. O agente do Console executa as ações que o NetApp Console precisa realizar para gerenciar sua infraestrutura de dados. O agente do Console consulta constantemente a camada de software como serviço NetApp Disaster Recovery em busca de quaisquer ações que precise executar.

Para NetApp Disaster Recovery, as ações executadas orquestram clusters VMware vCenter e instâncias de armazenamento ONTAP usando APIs nativas para cada serviço respectivo, a fim de fornecer proteção para VMs de produção em execução em um local on-premises. Embora o agente do Console possa ser instalado em qualquer local da sua rede, recomenda-se instalar o agente do Console no site de recuperação de desastres para NetApp Disaster Recovery. A instalação no site de recuperação de desastres garante que, em caso de falha do site primário, a interface do usuário do NetApp Console mantenha sua conexão com o agente do Console e possa orquestrar o processo de recuperação dentro desse site de recuperação de desastres.



== Instalação

* Para usar o NetApp Disaster Recovery, instale o agente do NetApp Console no modo padrão. Para saber mais sobre os tipos de instalação do agente do NetApp Console, visite  https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Saiba mais sobre os modos de implantação do NetApp Console"^].


Os passos específicos de instalação do agente do Console dependem do seu tipo de implantação. Consulte link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Saiba mais sobre os agentes do Console"^] para mais informações.


TIP: O método mais simples para instalar o agente do Console com Amazon AWS é usar o AWS Marketplace. Para obter detalhes sobre a instalação do agente do Console usando o AWS Marketplace, consulte  https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["Crie um agente do NetApp Console a partir do AWS Marketplace"^].
