---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: O NetApp Disaster Recovery é um serviço de recuperação de desastres baseado em nuvem que automatiza fluxos de trabalho de recuperação de desastres.  Você pode monitorar todos os trabalhos de recuperação de desastres e determinar seu progresso. 
---
= Monitorar trabalhos de NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Monitore os trabalhos do NetApp Disaster Recovery para acompanhar seu status e progresso.



[[view-jobs]]
== Ver empregos

*Função de NetApp Console necessária* É necessário ter a função de Super admin, Disaster recovery admin, Disaster recovery application admin ou Disaster recovery viewer para executar esta tarefa. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Saiba mais sobre funções e permissões de usuário no NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].

.Passos
. Faça login no https://console.netapp.com/["NetApp Console"^] .
. Na navegação à esquerda do NetApp Console , selecione *Proteção* > *Recuperação de desastres*.
. No menu, selecione *Monitoramento de tarefas*.
. Analise as tarefas, incluindo seus registros de data e hora e status.
. Para visualizar os detalhes de um trabalho, selecione a linha correspondente. Para baixar os detalhes do trabalho para revisão offline, selecione o menu de ações e, em seguida, selecione **Baixar detalhes do trabalho**.
+

TIP: Ao revisar os detalhes da tarefa, o NetApp Disaster Recovery mostra o usuário que iniciou a tarefa. Se o responsável estiver listado como "system", o NetApp Disaster Recovery iniciou a tarefa.

. Para atualizar as informações, selecione *Atualizar*.




[[cancel-a-job]]
== Cancelar um trabalho

Você pode cancelar uma tarefa em andamento ou que esteja na fila se estiver travada ou para priorizar uma operação pendente.

*Função de console NetApp necessária* A função de Super admin, Disaster recovery admin, Disaster recovery failover admin ou Disaster recovery application admin é necessária para executar esta tarefa. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Saiba mais sobre funções e permissões de usuário no NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].

.Passos
. Na barra de navegação esquerda do NetApp Console , selecione *Proteção* > *Recuperação de desastres*.
. No menu, selecione *Monitoramento de tarefas*.
. Na página de monitoramento de tarefas, anote o ID da tarefa que você deseja cancelar.
+
O trabalho deve estar no estado "Em andamento" ou "Na fila".

. Selecione o menu de ações e, em seguida, **Cancel job**.

