---
sidebar: sidebar 
permalink: use/task-appvault.html 
keywords: disaster recovery, appvault, update credentials, trident protect, kubernetes, edit endpoints 
summary: Gerenciar AppVaults em NetApp Disaster Recovery permite que você revise o status de conectividade dos seus AppVaults, assim como as credenciais e os endpoints dos AppVaults para garantir a continuidade dos seus planos de recuperação de desastres. 
---
= Gerencie AppVaults no NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
As cargas de trabalho de NetApp Disaster Recovery com Kubernetes utilizam o AppVault, um storage de nuvem onde o Trident Protect salva os dados de proteção do Kubernetes. Gerenciar os AppVaults permite que você revise o status de conectividade dos seus AppVaults, assim como as credenciais e os endpoints dos AppVaults para garantir a integridade dos seus planos de replicação.

*Função de console NetApp necessária* A função de Super admin, Disaster recovery admin ou Disaster recovery application admin é necessária para executar esta tarefa. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Saiba mais sobre funções e permissões de usuário no NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do NetApp Console para todos os serviços"^].



[[add-an-appvault]]
== Adicione um AppVault

Você pode adicionar um AppVault ao criar um plano de replicação para o Kubernetes ou criar um na página Configurações.

.Passos
. Em NetApp Disaster Recovery, selecione *Configurações* na barra lateral.
. No cartão AppVault, selecione *+ Adicionar AppVault*.
. Insira um *Nome* e selecione o *Agente do Console* ao qual o AppVault deve ser conectado.
. Selecione o provedor de nuvem para hospedar o *AppVault*.
. Com base no provedor selecionado, o Disaster Recovery preenche as assinaturas de cloud configuradas existentes.
+
Para o Azure, escolha a *Assinatura*, o *Grupo de recursos* e a *Conta de armazenamento*.

+
Para AWS, ONTAP S3 e StorageGRID, escolha a *Conta* ou *Credenciais* e o *Bucket*.

. Se você selecionou o ONTAP S3 ou o StorageGRID, pode adicionar credenciais opcionalmente. Selecione *Adicionar credenciais* para expandir as opções e, em seguida, adicione o *Nome da credencial*, o *FQDN do nó de gateway*, o número da *porta*, a *Chave de acesso* e a *Chave secreta*.
. Selecione **Adicionar**.




[[update-appvault-credentials]]
== Atualizar credenciais do AppVault

Se as credenciais do seu AppVault foram alteradas, atualize-as na página de Configurações para garantir a continuidade dos seus planos de replicação. A atualização das credenciais substituirá as chaves de cada AppVault que compartilha essa credencial.

.Passos
. Em NetApp Disaster Recovery, selecione *Configurações* na barra lateral.
. Selecione *Gerenciar AppVaults*.
. Encontre o AppVault que você deseja atualizar. No menu de ações, selecione *Atualizar*.
. Analise o número de AppVaults e planos de replicação afetados pela alteração.
. Insira a nova *Chave secreta* e a *Chave de acesso*.
. Selecione *Atualizar credenciais* para aplicar as alterações.




[[edit-an-appvault-endpoint]]
== Editar um endpoint AppVault

Se as configurações de conexão com o seu AppVault foram alteradas, atualize-as para garantir a continuidade dos seus planos de replicação para cargas de trabalho do Kubernetes.

.Passos
. Em NetApp Disaster Recovery, selecione *Configurações* na barra lateral.
. Selecione *Gerenciar AppVaults*.
. Localize o AppVault que você deseja editar. No menu de ações, selecione *Editar*.
. Insira o novo endpoint para o seu AppVault.
. Selecione *Salvar* para aplicar o novo endpoint.




[[delete-an-appvault]]
== Apague um AppVault

Se você não precisar mais de um AppVault, poderá excluí-lo.

.Passos
. Em NetApp Disaster Recovery, selecione *Configurações* na barra lateral.
. Selecione *Gerenciar AppVaults*.
. Localize o AppVault que você deseja excluir. No menu de ações, selecione *Excluir*.
. Na janela de diálogo, selecione *Excluir* para confirmar a ação.

