---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery 
summary: Antes de usar o NetApp Disaster Recovery, certifique-se de que seu ambiente atenda aos requisitos de armazenamento ONTAP , cluster VMware vCenter e NetApp Console . 
---
= Pré-requisitos do NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Antes de usar o NetApp Disaster Recovery, certifique-se de que seu ambiente atenda aos requisitos de armazenamento ONTAP , cluster VMware vCenter e NetApp Console .



== Versões de software

[cols="35,55a"]
|===
| Componente | Versão mínima 


| Amazon FSx for NetApp ONTAP  a| 
Última versão disponível



| Google Cloud VMware Engine usando Google Cloud NetApp Volumes  a| 
Última versão disponível



| Software ONTAP  a| 
ONTAP 9.10.0 ou posterior



| VMware Cloud para AWS  a| 
Última versão disponível



| VMware vCenter local  a| 
7.0u3 ou posterior

|===


== Pré-requisitos e considerações do Google Cloud

Ao utilizar o Disaster Recovery no Google Cloud VMware Engine com o Google Cloud NetApp Volumes, certifique-se de configurar as permissões corretas e seguir as considerações indicadas.

* Entre em contato com a equipe de SRE do Google para adicionar os seguintes itens à lista de permissões:
+
** API de sincronização para transferir snapshots do armazenamento local para o Google Cloud NetApp Volumes.
** O projeto do Google com o mecanismo da VMware para criar, montar e desmontar armazenamentos de dados.


* Você develink:https://docs.google.com/forms/d/1zuaHu437MNpUf8i5oByK-OTLWXcNIg0es9t036riYRc/viewform?edit_requested=true["Envie uma solicitação para adicionar seus volumes à lista de permissões para replicação híbrida."^] .
* Esteja ciente dolink:https://docs.cloud.google.com/netapp/volumes/docs/quotas["Cota e limites do Google Cloud NetApp Volumes"^] .
* Você só pode adicionar um volume ou armazenamento de dados a um plano de replicação.
* Analise olink:../release-notes/dr-limitations.html#limitations-with-google-cloud-netapp-volumes["limitações"] .


**Considerações sobre failover**

* O failover só é compatível com a versão snapshot mais recente.  Se necessário, você pode criar um novo instantâneo durante a captura de um novo instantâneo (ou seja, a opção de instantâneo seletivo deve estar desativada).
* Não é possível criar um novo snapshot após um failover.
* Não é possível manter e reconciliar snapshots após um failover.


**Considerações sobre planos de contingência**

* O failback só é possível com a opção de snapshot seletivo.  Não é possível realizar um failback tirando um novo snapshot.
* Se você remover o emparelhamento de cluster entre o armazenamento local e os clusters de armazenamento do Google Cloud NetApp Volumes , será necessário limpar manualmente a entrada de emparelhamento do cluster e da VM de armazenamento no cluster local. Para mais informações, consulte link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-delete.html["Excluir um relacionamento de pares do servidor virtual"^].




=== Permissões do Google Cloud

A entidade de serviço no Google Cloud deve ter atribuídas as seguintes funções ou permissões equivalentes:

* link:https://docs.cloud.google.com/compute/docs/access/iam["Função de Administrador de Computação"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["Permissões do Google Cloud para o NetApp Console"^]
* link:https://docs.cloud.google.com/iam/docs/roles-permissions/netapp["Administrador de Google Cloud NetApp Volumes"]
* link:https://docs.cloud.google.com/vmware-engine/docs/iam#vmware-engine-roles["Administrador de serviço do VMware Engine"^]




=== Permissões do NetApp Console

O usuário do NetApp Console deve ter as seguintes funções:

* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-gcnv-roles.html["Administrador do Google Cloud NetApp Volumes"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html#data-service-roles["Administrador do SnapCenter"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Administrador de failover de recuperação de desastres"^]




== Pré-requisitos de armazenamento ONTAP

Esses pré-requisitos se aplicam ao ONTAP ou ao Amazon FSX para instâncias do NetApp ONTAP .

* Os clusters de origem e destino devem ter um relacionamento de pares.
* O SVM que hospeda os volumes de recuperação de desastres deve existir no cluster de destino.
* O SVM de origem e o SVM de destino devem ter um relacionamento de mesmo nível.
* Se estiver implantando com o Amazon FSx for NetApp ONTAP, o seguinte pré-requisito se aplica:
+
** Uma instância do Amazon FSx for NetApp ONTAP para hospedar datastores do VMware DR deve existir na sua VPC. Para começar, vejalink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["a documentação do Amazon FSx para ONTAP"^] .






== Pré-requisitos dos clusters VMware vCenter

Esses pré-requisitos se aplicam aos clusters vCenter locais e ao data center definido por software (SDDC) do VMware Cloud for AWS.

* Análiselink:../reference/vcenter-privileges.html["Privilégios do vCenter"] necessário para NetApp Disaster Recovery.
* Todos os clusters VMware que você deseja que o NetApp Disaster Recovery gerencie usam volumes ONTAP para hospedar quaisquer VMs que você deseja proteger.
* Todos os datastores VMware a serem gerenciados pelo NetApp Disaster Recovery devem usar um dos seguintes protocolos:
+
** NFS
** VMFS usando o protocolo iSCSI ou FC


* VMware vSphere versão 7.0 Atualização 3 (7.0v3) ou posterior
* Se você estiver usando o VMware Cloud SDDC, estes pré-requisitos se aplicam.
+
** No VMware Cloud Console, use as funções de serviço de Administrador e Administrador do NSX Cloud.  Use também o proprietário da organização para a função Organização. Consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Usando o VMware Cloud Foundations com AWS FSx para documentação do NetApp ONTAP"^] .
** Vincule o VMware Cloud SDDC ao Amazon FSx for NetApp ONTAP . Consulte https://vmc.techzone.vmware.com/fsx-guide#overview["Integração do VMware Cloud on AWS com o Amazon FSx for NetApp ONTAP"^] .






== Pré-requisitos do NetApp Console



=== Comece a usar o NetApp Console

Se você ainda não o fez, https://docs.netapp.com/us-en/console-setup-admin/task-sign-up-saas.html["inscreva-se no NetApp Console e crie uma organização"^] .



=== Reúna credenciais para ONTAP e VMware

* As credenciais do Amazon FSx para ONTAP e da AWS devem ser adicionadas ao sistema dentro do projeto do NetApp Console que gerencia o NetApp Disaster Recovery.
* O NetApp Disaster Recovery requer credenciais do vCenter.  Você insere as credenciais do vCenter ao adicionar um site no NetApp Disaster Recovery.
+
Para obter uma lista de privilégios do vCenter necessários, consultelink:../reference/vcenter-privileges.html["Privilégios do vCenter necessários para NetApp Disaster Recovery"] .  Para obter instruções sobre como adicionar um site, consultelink:../use/sites-add.html["Adicionar um site"] .





=== Crie o agente do NetApp Console

O agente do Console é um componente de software que permite que o Console se comunique com seus clusters de armazenamento ONTAP e VMware vCenter. É necessário para que a Recuperação de Desastres funcione corretamente. O agente reside em sua rede privada (seja um data center local ou uma VPC na nuvem) e se comunica com suas instâncias de armazenamento ONTAP e quaisquer componentes adicionais de servidor e aplicativo. Para recuperação de desastres, este é o acesso aos seus clusters vCenter gerenciados.

Um agente do Console deve ser configurado no NetApp Console.  Quando você usa o agente, ele inclui os recursos apropriados para o serviço de Recuperação de Desastres.

* O NetApp Disaster Recovery funciona apenas com a implantação do agente no modo padrão. Ver https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Introdução ao NetApp Console no modo padrão"^] .
* Certifique-se de que os vCenters de origem e de destino usem o mesmo agente de console.
* Tipo de agente de console necessário:
+
** *Recuperação de desastres local para local*: Instale o agente local do Console no site de recuperação de desastres. Usando esse método, uma falha no site principal não impede que o serviço reinicie seus recursos virtuais no site de DR. Consulte https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-on-prem.html["Instalar e configurar o agente do Console no local"^] .
** *No local para AWS*: Instale o agente do Console para AWS na sua VPC da AWS. Consulte https://docs.netapp.com/us-en/console-setup-admin/concept-install-options-aws.html["Opções de instalação do agente de console na AWS"^] .
+

TIP: Para locais para locais, use o agente do Console local.  Para o local na AWS, use o agente do Console da AWS, que tem acesso ao vCenter local de origem e ao vCenter local de destino.

** O agente de console instalado deve ser capaz de acessar quaisquer instâncias de cluster do VMware vCenter e hosts ESXi gerenciados por esses clusters do vCenter que serão gerenciados pela Recuperação de Desastres.


* Todos os arrays ONTAP a serem gerenciados pelo NetApp Disaster Recovery devem ser adicionados a qualquer sistema dentro do projeto do NetApp Console que será usado para gerenciar o NetApp Disaster Recovery.
+
Ver https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Descubra clusters ONTAP locais"^] .

* Para obter informações sobre como configurar um proxy inteligente para o NetApp Disaster Recovery, consultelink:../get-started/dr-setup.html["Configure sua infraestrutura para NetApp Disaster Recovery"] .




== Pré-requisitos de carga de trabalho

Para garantir que os processos de consistência de aplicativos sejam bem-sucedidos, aplique estes pré-requisitos:

* Certifique-se de que as ferramentas VMware (ou ferramentas Open VM) estejam em execução nas VMs que serão protegidas.
* Para máquinas virtuais Windows que executam o Microsoft SQL Server, o Oracle Database ou ambos, os gravadores VSS dos bancos de dados devem estar habilitados.
* Os bancos de dados Oracle que estão sendo executados em um sistema operacional Linux devem ter a autenticação de usuário do sistema operacional habilitada para a função SYSDBA do banco de dados Oracle.

