---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Para usar o NetApp Disaster Recovery, siga algumas etapas para configurá-lo. 
---
= Configure sua infraestrutura para NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Para usar o NetApp Disaster Recovery, conclua algumas etapas de configuração no NetApp Console e em seu ambiente de recuperação de desastres compatível.


TIP: Análiselink:../get-started/dr-prerequisites.html["pré-requisitos"] para garantir que seu sistema esteja pronto.



[[supported-infrastructures]]
== Infraestruturas suportadas

Você pode usar o NetApp Disaster Recovery nas seguintes infraestruturas:

* Recuperação de desastres (DR) em nuvem híbrida que replica um datacenter VMware local com ONTAP para uma infraestrutura de DR da AWS baseada em VMware Cloud on AWS ou Elastic VMware Service (Exchange Virtual Server) e Amazon FSx for NetApp ONTAP.
* DR de nuvem privada que replica um VMware mais ONTAP vCenter local para outro VMware mais ONTAP vCenter local.
* Cloud DR que replica uma infraestrutura de DR da AWS baseada em VMware Cloud on AWS ou Exchange Virtual Server para outra infraestrutura de DR baseada na AWS usando FSx for NetApp ONTAP.
* Recuperação de desastres (DR) em nuvem híbrida que replica um datacenter VMware local com ONTAP para uma infraestrutura de DR do Google baseada no Google Cloud VMware Engine e no Google Cloud NetApp Volumes.




[[hybrid-cloud-with-vmware-cloud-and-amazon-fsx-for-netapp-ontap]]
== Nuvem híbrida com VMware Cloud e Amazon FSx for NetApp ONTAP

Este método consiste em uma infraestrutura vCenter de produção local usando datastores hospedados em volumes ONTAP FlexVol usando um protocolo NFS.  O site de DR consiste em uma ou mais instâncias do VMware Cloud SDDC usando armazenamentos de dados hospedados em volumes FlexVol fornecidos por uma ou mais instâncias do FSx for ONTAP usando um protocolo NFS.

Os sites de produção e de recuperação de desastres (DR) são conectados por uma conexão segura compatível com a AWS. Os tipos de conexão comuns são uma VPN segura (privada ou fornecida pela AWS), AWS Direct Connect ou outros métodos de interconexão aprovados.

Para recuperação de desastres envolvendo infraestrutura de nuvem da AWS, você deve usar o agente do Console para AWS.  O agente deve ser instalado na mesma VPC que a instância do FSx para ONTAP .  Se instâncias adicionais do FSx for ONTAP foram implantadas em outras VPCs, a VPC que hospeda o agente deve ter acesso às outras VPCs.



[[aws-availability-zones]]
=== Zonas de disponibilidade da AWS

A AWS oferece suporte à implantação de soluções em uma ou mais Zonas de Disponibilidade (AZs) dentro de uma região. A NetApp Disaster Recovery utiliza dois serviços hospedados na AWS: VMware Cloud on AWS e Amazon FSx for NetApp ONTAP.

* *VMware Cloud for AWS*: oferece suporte à implantação em um ambiente SDDC de cluster stretch de zona única ou dupla. NetApp Disaster Recovery oferece suporte apenas a implantações SDDC de zona única para VMware Cloud on AWS.
* *AWS FSx for NetApp ONTAP*: quando o Amazon FSx for NetApp ONTAP é implantado em uma configuração multi-AZ, cada volume pertence a um sistema de arquivos do FSx for ONTAP, e os dados são espelhados para o segundo sistema de arquivos. O FSx for ONTAP pode ser implantado em configurações single-AZ ou multi-AZ. O NetApp Disaster Recovery suporta ambos os modelos de implantação.


*MELHOR PRÁTICA*: Para a configuração do site de DR na AWS, a NetApp recomenda o uso de implantações em uma única AZ tanto para o VMware Cloud quanto para o AWS FSx for ONTAP. Como a AWS está sendo usada para recuperação de desastres, não há vantagem em introduzir múltiplas Zonas de Disponibilidade. Implantações em múltiplas Zonas de Disponibilidade podem aumentar o custo e a complexidade.



[[on-premises-to-aws]]
=== No local para AWS

A AWS fornece os seguintes métodos para conectar datacenters privados à nuvem AWS.  Cada solução tem seus benefícios e considerações de custo.

* *AWS Direct Connect*: Esta é uma interconexão da nuvem AWS localizada na mesma área geográfica que seu data center privado e fornecida por um parceiro da AWS. Essa solução oferece uma conexão segura e privada entre seu data center local e a nuvem da AWS sem a necessidade de uma conexão pública com a internet. Este é o método de conexão mais direto e eficiente oferecido pela AWS.
* *AWS Internet Gateway*: fornece conectividade pública entre recursos de nuvem da AWS e recursos de computação externos.  Esse tipo de conexão normalmente é usado para fornecer serviços a clientes externos, como serviços HTTP/HTTPS, onde a segurança não é um requisito.  Não há controle de qualidade de serviço, segurança ou garantia de conectividade.  Por esse motivo, esse método de conexão não é recomendado para conectar um datacenter de produção à nuvem.
* *VPN Site-to-Site da AWS*: essa conexão de rede privada virtual pode fornecer conectividade segura por meio de um provedor de serviços de internet público. A VPN criptografa e descriptografa todos os dados que trafegam de e para a nuvem da AWS. As VPNs podem ser baseadas em software ou baseadas em hardware. Para aplicações corporativas, o provedor de serviços de internet (ISP) público deve oferecer garantias de qualidade de serviço para assegurar que haja largura de banda e latência adequadas para a replicação de DR.


*PRÁTICA RECOMENDADA*: Para configuração de site de DR da AWS, a NetApp recomenda usar o AWS Direct Connect.  Esta solução oferece o mais alto desempenho e segurança para aplicativos corporativos.  Caso não esteja disponível, uma conexão ISP pública de alto desempenho juntamente com uma VPN deve ser usada.  Certifique-se de que o ISP ofereça níveis de serviço de QoS comerciais para garantir um desempenho de rede adequado.



[[vpc-to-vpc-interconnections]]
=== Interconexões VPC para VPC

A AWS oferece os seguintes tipos de interconexões de VPC para VPC.  Cada solução tem seus benefícios e considerações de custo.

* *VPC Peering*: Esta é uma conexão privada entre duas VPCs.  É o método de conexão mais direto e eficiente oferecido pela AWS.  O peering de VPC pode ser usado para conectar VPCs na mesma região da AWS ou em regiões diferentes.
* *AWS Internet Gateway*: normalmente é usado para fornecer conexões entre recursos do AWS VPC e recursos e endpoints que não são da AWS.  Todo o tráfego segue um caminho "em grampo" em que o tráfego da VPC destinado a outra VPC sai da infraestrutura da AWS pelo gateway da Internet e retorna à infraestrutura da AWS pelo mesmo gateway ou por um diferente.  Este não é um tipo de conexão VPC adequado para soluções VMware corporativas.
* *AWS Transit Gateway*: Este é um tipo de conexão centralizada baseada em roteador que permite que cada VPC se conecte a um único gateway central, que atua como um hub central para todo o tráfego de VPC para VPC.  Isso também pode ser conectado à sua solução VPN para permitir que recursos do datacenter local acessem recursos hospedados no AWS VPC.  Esse tipo de conexão normalmente exige um custo adicional para ser implementado.


*MELHOR PRÁTICA*: Para soluções de DR que utilizam o VMware Cloud e uma única VPC do FSx for ONTAP, a NetApp recomenda usar o peering de VPC. Se várias VPCs do FSx for ONTAP forem implantadas, recomendamos usar um AWS Transit Gateway para reduzir a sobrecarga no gerenciamento de múltiplas conexões de peering de VPC.



[[get-ready-for-on-premises-to-cloud-protection-using-aws]]
=== Prepare-se para a proteção local para a nuvem usando a AWS

Para configurar o NetApp Disaster Recovery para proteção local para a nuvem usando a AWS, você precisa configurar o seguinte:

* Configurar o AWS FSx para NetApp ONTAP
* Configurar o VMware Cloud no AWS SDDC




==== Configurar o AWS FSx para NetApp ONTAP

* Crie um sistema de arquivos Amazon FSx for NetApp ONTAP .
+
** Provisione e configure o FSx para ONTAP.  O Amazon FSx for NetApp ONTAP é um serviço totalmente gerenciado que fornece armazenamento de arquivos altamente confiável, escalável, de alto desempenho e rico em recursos, criado no sistema de arquivos NetApp ONTAP .
** Siga os passos em https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["Relatório técnico 4938: Monte o Amazon FSx ONTAP como um armazenamento de dados NFS com o VMware Cloud na AWS"^] e https://docs.netapp.com/us-en/storage-management-fsx-ontap/start/task-getting-started-fsx.html["Início rápido para Amazon FSx for NetApp ONTAP"] Para provisionar e configurar o FSx para ONTAP.


* Adicione o Amazon FSx para ONTAP ao sistema e adicione credenciais da AWS para o FSx para ONTAP.
* Crie ou verifique sua SVM de destino do ONTAP na instância AWS FSx for ONTAP.
* Configure a replicação entre seu cluster ONTAP local de origem e sua instância do FSx for ONTAP no NetApp Console.


Consulte https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["como configurar um FSx para sistema ONTAP"^] para etapas detalhadas.



==== Configurar o VMware Cloud no AWS SDDC

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud na AWS"^]fornece uma experiência nativa em nuvem para cargas de trabalho baseadas em VMware no ecossistema da AWS. Cada data center definido por software (SDDC) da VMware é executado em uma Amazon Virtual Private Cloud (VPC) e fornece uma pilha VMware completa (incluindo o vCenter Server), rede definida por software NSX-T, armazenamento definido por software vSAN e um ou mais hosts ESXi que fornecem recursos de computação e armazenamento para as cargas de trabalho.

Para configurar um ambiente VMware Cloud na AWS, siga as etapas em https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["Implantar e configurar o ambiente de virtualização na AWS"^] . Um conjunto de luzes piloto também pode ser usado para fins de recuperação de desastres.



[[private-cloud]]
== Nuvem privada

Você pode usar o NetApp Disaster Recovery para proteger VMs VMware hospedadas em um ou mais clusters vCenter replicando datastores de VM para outro cluster vCenter no mesmo datacenter privado ou em um datacenter privado ou colocalizado remoto.

Para situações de local para local, instale o agente do Console em um dos sites físicos.

O Disaster Recovery oferece suporte à replicação de site para site usando Ethernet e TCP/IP.  Certifique-se de que haja largura de banda adequada disponível para suportar taxas de alteração de dados nas VMs do site de produção, para que todas as alterações possam ser replicadas no site de DR dentro do período do Objetivo de Ponto de Recuperação (RPO).



[[get-ready-for-on-premises-to-on-premises-protection]]
=== Prepare-se para proteção local para local

Certifique-se de que os seguintes requisitos sejam atendidos antes de configurar o NetApp Disaster Recovery para proteção local para local:

* Armazenamento ONTAP
+
** Certifique-se de ter credenciais ONTAP .
** Crie ou verifique seu site de recuperação de desastres.
** Crie ou verifique seu ONTAP SVM de destino.
** Certifique-se de que seus SVMs ONTAP de origem e destino estejam pareados.


* Clusters do vCenter
+
** Certifique-se de que as VMs que você deseja proteger estejam hospedadas em datastores NFS (usando volumes ONTAP NFS) ou datastores VMFS (usando LUNs iSCSI da NetApp ).
** Análiselink:../reference/vcenter-privileges.html["Privilégios do vCenter"] necessário para NetApp Disaster Recovery.
** Crie uma conta de usuário de recuperação de desastres (não a conta de administrador padrão do vCenter) e atribua os privilégios do vCenter à conta.






[[intelligent-proxy-support]]
=== Suporte a proxy inteligente

O agente do NetApp Console oferece suporte ao proxy inteligente.  O proxy inteligente é uma maneira leve, segura e eficiente de conectar seu ambiente local ao NetApp Console.  Ele fornece uma conexão segura entre seu sistema e o serviço do Console sem exigir uma VPN ou acesso direto à Internet.  Essa implementação de proxy otimizada descarrega o tráfego de API dentro da rede local.

Quando um proxy é configurado, o NetApp Disaster Recovery tenta se comunicar diretamente com o VMware ou o ONTAP e usa o proxy configurado se a comunicação direta falhar.

A implementação do proxy do NetApp Disaster Recovery requer comunicação pela porta 443 entre o agente do NetApp Console e quaisquer servidores vCenter e matrizes ONTAP usando um protocolo HTTPS. O agente do NetApp Disaster Recovery dentro do agente do NetApp Console se comunica diretamente com o VMware vSphere, o servidor vCenter ou o ONTAP ao realizar ações.

Para obter mais informações sobre a configuração geral de proxy no NetApp Console, consulte https://docs.netapp.com/us-en/console-setup-admin/task-configuring-proxy.html["Configurar o agente do Console para usar um servidor proxy"^] .
